version: "3.8"

services:
  app_blue:
    image: yimikaade/wonderful:devops-stage-two
    container_name: app_blue
    environment:
      - PORT=3000
    ports:
      - "8081:3000"
    healthcheck:
      test: ["CMD", "node", "-e", "http.get('http://localhost:3000/version', r => process.exit(r.statusCode === 200 ? 0 : 1))"]
      interval: 10s
      timeout: 3s
      retries: 3

  app_green:
    image: yimikaade/wonderful:devops-stage-two
    container_name: app_green
    environment:
      - PORT=3000
    ports:
      - "8082:3000"
    healthcheck:
      test: ["CMD", "node", "-e", "http.get('http://localhost:3000/version', r => process.exit(r.statusCode === 200 ? 0 : 1))"]
      interval: 10s
      timeout: 3s
      retries: 3

  bg_nginx:
    image: nginx:latest
    container_name: bg_nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf.template:/etc/nginx/templates/default.conf.template
    environment:
      - ACTIVE_POOL=blue
      - PORT=3000
    depends_on:
      - app_blue
      - app_green

  alert_watcher:
    build: ./watcher
    container_name: alert_watcher
    environment:
      - SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL}
      - ERROR_THRESHOLD=2.0
      - NGINX_URL=http://bg_nginx
    depends_on:
      - bg_nginx
